language: generic
osx_image: xcode7.3
os:
  - linux
  - osx
sudo: required
dist: trusty
before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install carthage ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then carthage bootstrap ; fi
install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then SWIFT_DIR=tests ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install clang uuid-dev libjson-c-dev ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then mkdir $SWIFT_DIR ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then curl https://swift.org/builds/development/ubuntu1404/$SWIFT_VERSION/$SWIFT_VERSION-ubuntu14.04.tar.gz -s | tar xz -C $SWIFT_DIR &> /dev/null ; fi
env:
  - SWIFT_VERSION=swift-DEVELOPMENT-SNAPSHOT-2016-02-25-a
script:
  - uname
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool test -workspace SwiftFoundation.xcworkspace -scheme "SwiftFoundation OS X" -sdk macosx ONLY_ACTIVE_ARCH=NO ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then xctool build -workspace SwiftFoundation.xcworkspace -scheme "SwiftFoundation iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO ; fi
  
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export PATH=$(pwd)/tests/$SWIFT_VERSION-ubuntu14.04/usr/bin:"${PATH}" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then swift build -c release ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then .build/release/UnitTests ; fi
  